# Generated environment variables
SHELL: "/usr/bin/bash"
NUMBER_OF_PROCESSORS: "4"
FPS_BROWSER_USER_PROFILE_STRING: "Default"
COLORTERM: "truecolor"
PROCESSOR_LEVEL: "6"
TERM_PROGRAM_VERSION: "1.81.1"
MINGW_PREFIX: "/mingw64"
PKG_CONFIG_PATH: "/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig"
USERDOMAIN_ROAMINGPROFILE: "DESKTOP-TGMIEVC"
HOSTNAME: "DESKTOP-TGMIEVC"
PROGRAMFILES: "C:\Program Files"
MSYSTEM: "MINGW64"
ChocolateyInstall: "C:\ProgramData\chocolatey"
PATHEXT: ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW"
ORIGINAL_TEMP: "/tmp"
MINGW_CHOST: "x86_64-w64-mingw32"
OS: "Windows_NT"
HOMEDRIVE: "C:"
MSYSTEM_CARCH: "x86_64"
USERDOMAIN: "DESKTOP-TGMIEVC"
PWD: "/d/source-code/hello-world"
USERPROFILE: "C:\Users\EGD"
MANPATH: "/mingw64/local/man:/mingw64/share/man:/usr/local/man:/usr/share/man:/usr/man:/share/man"
VSCODE_GIT_ASKPASS_NODE: "C:\Users\EGD\AppData\Local\Programs\Microsoft VS Code\Code.exe"
MINGW_PACKAGE_PREFIX: "mingw-w64-x86_64"
ALLUSERSPROFILE: "C:\ProgramData"
ORIGINAL_PATH: "/mingw64/bin:/usr/bin:/c/Users/EGD/bin:/c/Python311/Scripts:/c/Python311:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/Docker/Docker/resources/bin:/cmd:/c/Program Files/nodejs:/c/ProgramData/chocolatey/bin:/c/Users/EGD/AppData/Local/Microsoft/WindowsApps:/c/Users/EGD/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/EGD/AppData/Roaming/npm:/c/Users/EGD/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin"
CommonProgramW6432: "C:\Program Files\Common Files"
HOME: "/c/Users/EGD"
USERNAME: "EGD"
SSH_ASKPASS: "/mingw64/bin/git-askpass.exe"
LANG: "en_US.UTF-8"
PLINK_PROTOCOL: "ssh"
OneDrive: "C:\Users\EGD\OneDrive"
COMSPEC: "C:\Windows\system32\cmd.exe"
TMPDIR: "/tmp"
GIT_ASKPASS: "c:\Users\EGD\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh"
APPDATA: "C:\Users\EGD\AppData\Roaming"
SYSTEMROOT: "C:\Windows"
LOCALAPPDATA: "C:\Users\EGD\AppData\Local"
COMPUTERNAME: "DESKTOP-TGMIEVC"
INFOPATH: "/mingw64/local/info:/mingw64/share/info:/usr/local/info:/usr/share/info:/usr/info:/share/info"
VSCODE_GIT_ASKPASS_EXTRA_ARGS: "--ms-enable-electron-run-as-node"
TERM: "xterm-256color"
LOGONSERVER: "\\DESKTOP-TGMIEVC"
ZES_ENABLE_SYSMAN: "1"
ACLOCAL_PATH: "/mingw64/share/aclocal:/usr/share/aclocal"
PSModulePath: "C:\Users\EGD\Documents\WindowsPowerShell\Modules;C:\Users\EGD\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\PowerShell"
VSCODE_GIT_IPC_HANDLE: "\\.\pipe\vscode-git-657a5658ed-sock"
TEMP: "/tmp"
MSYSTEM_CHOST: "x86_64-w64-mingw32"
DISPLAY: "needs-to-be-defined"
SHLVL: "2"
ORIGINAL_TMP: "/tmp"
PROCESSOR_REVISION: "5e03"
DriverData: "C:\Windows\System32\Drivers\DriverData"
COMMONPROGRAMFILES: "C:\Program Files\Common Files"
EXEPATH: "C:\Program Files\Git\bin"
PROCESSOR_IDENTIFIER: "Intel64 Family 6 Model 94 Stepping 3, GenuineIntel"
SESSIONNAME: "Console"
PKG_CONFIG_SYSTEM_LIBRARY_PATH: "/mingw64/lib"
CHROME_CRASHPAD_PIPE_NAME: "\\.\pipe\LOCAL\crashpad_11808_GDNIJQNXJUFSWHHB"
VSCODE_GIT_ASKPASS_MAIN: "c:\Users\EGD\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js"
HOMEPATH: "\Users\EGD"
TMP: "/tmp"
CONFIG_SITE: "/etc/config.site"
PATH: "/c/Users/EGD/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/EGD/bin:/c/Python311/Scripts:/c/Python311:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/Docker/Docker/resources/bin:/cmd:/c/Program Files/nodejs:/c/ProgramData/chocolatey/bin:/c/Users/EGD/AppData/Local/Microsoft/WindowsApps:/c/Users/EGD/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/EGD/AppData/Roaming/npm:/c/Users/EGD/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin:/usr/bin/vendor_perl:/usr/bin/core_perl"
ProgramW6432: "C:\Program Files"
MSYSTEM_PREFIX: "/mingw64"
ORIGINAL_XDG_CURRENT_DESKTOP: "undefined"
WINDIR: "C:\Windows"
FPS_BROWSER_APP_PROFILE_STRING: "Internet Explorer"
PROCESSOR_ARCHITECTURE: "AMD64"
PUBLIC: "C:\Users\Public"
PKG_CONFIG_SYSTEM_INCLUDE_PATH: "/mingw64/include"
SYSTEMDRIVE: "C:"
TERM_PROGRAM: "vscode"
ProgramData: "C:\ProgramData"
ChocolateyLastPathUpdate: "133358486613149941"
_: "/usr/bin/env"
