# Generated environment variables
ACLOCAL_PATH: "/mingw64/share/aclocal:/usr/share/aclocal"
ALLUSERSPROFILE: "C:\ProgramData"
APPDATA: "C:\Users\EGD\AppData\Roaming"
CHROME_CRASHPAD_PIPE_NAME: "\\.\pipe\LOCAL\crashpad_11808_GDNIJQNXJUFSWHHB"
COLORTERM: "truecolor"
COMMONPROGRAMFILES: "C:\Program Files\Common Files"
COMPUTERNAME: "DESKTOP-TGMIEVC"
COMSPEC: "C:\Windows\system32\cmd.exe"
CONFIG_SITE: "/etc/config.site"
ChocolateyInstall: "C:\ProgramData\chocolatey"
ChocolateyLastPathUpdate: "133358486613149941"
CommonProgramW6432: "C:\Program Files\Common Files"
DISPLAY: "needs-to-be-defined"
DriverData: "C:\Windows\System32\Drivers\DriverData"
EXEPATH: "C:\Program Files\Git\bin"
FPS_BROWSER_APP_PROFILE_STRING: "Internet Explorer"
FPS_BROWSER_USER_PROFILE_STRING: "Default"
GIT_ASKPASS: "c:\Users\EGD\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh"
HOME: "/c/Users/EGD"
HOMEDRIVE: "C:"
HOMEPATH: "\Users\EGD"
HOSTNAME: "DESKTOP-TGMIEVC"
INFOPATH: "/mingw64/local/info:/mingw64/share/info:/usr/local/info:/usr/share/info:/usr/info:/share/info"
LANG: "en_US.UTF-8"
LOCALAPPDATA: "C:\Users\EGD\AppData\Local"
LOGONSERVER: "\\DESKTOP-TGMIEVC"
MANPATH: "/mingw64/local/man:/mingw64/share/man:/usr/local/man:/usr/share/man:/usr/man:/share/man"
MINGW_CHOST: "x86_64-w64-mingw32"
MINGW_PACKAGE_PREFIX: "mingw-w64-x86_64"
MINGW_PREFIX: "/mingw64"
MSYSTEM: "MINGW64"
MSYSTEM_CARCH: "x86_64"
MSYSTEM_CHOST: "x86_64-w64-mingw32"
MSYSTEM_PREFIX: "/mingw64"
NUMBER_OF_PROCESSORS: "4"
ORIGINAL_PATH: "/mingw64/bin:/usr/bin:/c/Users/EGD/bin:/c/Python311/Scripts:/c/Python311:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/Docker/Docker/resources/bin:/cmd:/c/Program Files/nodejs:/c/ProgramData/chocolatey/bin:/c/Users/EGD/AppData/Local/Microsoft/WindowsApps:/c/Users/EGD/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/EGD/AppData/Roaming/npm:/c/Users/EGD/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin"
ORIGINAL_TEMP: "/tmp"
ORIGINAL_TMP: "/tmp"
ORIGINAL_XDG_CURRENT_DESKTOP: "undefined"
OS: "Windows_NT"
OneDrive: "C:\Users\EGD\OneDrive"
PATH: "/c/Users/EGD/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/EGD/bin:/c/Python311/Scripts:/c/Python311:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/Docker/Docker/resources/bin:/cmd:/c/Program Files/nodejs:/c/ProgramData/chocolatey/bin:/c/Users/EGD/AppData/Local/Microsoft/WindowsApps:/c/Users/EGD/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/EGD/AppData/Roaming/npm:/c/Users/EGD/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin:/usr/bin/vendor_perl:/usr/bin/core_perl"
PATHEXT: ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW"
PKG_CONFIG_PATH: "/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig"
PKG_CONFIG_SYSTEM_INCLUDE_PATH: "/mingw64/include"
PKG_CONFIG_SYSTEM_LIBRARY_PATH: "/mingw64/lib"
PLINK_PROTOCOL: "ssh"
PROCESSOR_ARCHITECTURE: "AMD64"
PROCESSOR_IDENTIFIER: "Intel64 Family 6 Model 94 Stepping 3, GenuineIntel"
PROCESSOR_LEVEL: "6"
PROCESSOR_REVISION: "5e03"
PROGRAMFILES: "C:\Program Files"
PSModulePath: "C:\Users\EGD\Documents\WindowsPowerShell\Modules;C:\Users\EGD\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\PowerShell"
PUBLIC: "C:\Users\Public"
PWD: "/d/source-code/hello-world"
ProgramData: "C:\ProgramData"
ProgramW6432: "C:\Program Files"
SESSIONNAME: "Console"
SHELL: "/usr/bin/bash"
SHLVL: "2"
SSH_ASKPASS: "/mingw64/bin/git-askpass.exe"
SYSTEMDRIVE: "C:"
SYSTEMROOT: "C:\Windows"
TEMP: "/tmp"
TERM: "xterm-256color"
TERM_PROGRAM: "vscode"
TERM_PROGRAM_VERSION: "1.81.1"
TMP: "/tmp"
TMPDIR: "/tmp"
USERDOMAIN: "DESKTOP-TGMIEVC"
USERDOMAIN_ROAMINGPROFILE: "DESKTOP-TGMIEVC"
USERNAME: "EGD"
USERPROFILE: "C:\Users\EGD"
VSCODE_GIT_ASKPASS_EXTRA_ARGS: "--ms-enable-electron-run-as-node"
VSCODE_GIT_ASKPASS_MAIN: "c:\Users\EGD\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js"
VSCODE_GIT_ASKPASS_NODE: "C:\Users\EGD\AppData\Local\Programs\Microsoft VS Code\Code.exe"
VSCODE_GIT_IPC_HANDLE: "\\.\pipe\vscode-git-657a5658ed-sock"
WINDIR: "C:\Windows"
ZES_ENABLE_SYSMAN: "1"
