name: develop

on:
  workflow_dispatch:
#  pull_request:
#    branches:
#      - "develop"
  push:
    branches:
      - "develop"
jobs:
  build_deploy:

    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        
      - name: Export Variables
        id: EXPORT_VARIABLE
        shell: bash
        run: |
          echo "develop"
