name: Build and Push to Google Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"
      - "production"
      - "feature/*"  # Các nhánh feature

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          env | grep -E "^[A-Za-z_][A-Za-z0-9_]*=" | while read -r line; do
          key=$(echo "$line" | cut -d= -f1)
          value=$(echo "$line" | cut -d= -f2-)
          echo "${key}: \"${value}\"" >> $yaml_file
          done
