name: Build and Push to Google Cloud run

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "develop"
  push:
    branches:
      - "develop"
jobs:
  build_deploy:

    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Build container image
        run: |
          echo "${{env.NODE_ENV}}"
          echo ${{env.test}}
          echo ${{ secrets.REGION }}