on:
  workflow_dispatch:
  pull_request:
    branches:
      - "develop"
  push:
    branches:
      - "develop"
      - "production"  # Thêm nhánh production vào đây

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set NODE_ENV as Environment Variable
        run: echo "NODE_ENV=${{ env.NODE_ENV }}" >> $GITHUB_ENV
  another_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use NODE_ENV in Another Job
        run: |
          echo "Using NODE_ENV from Previous Job: $NODE_ENV"