name: Dynamic Workflow

on:
  push:
    branches:
      - "*"

jobs:
  use_dynamic_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine workflow file based on branch
        id: determine_workflow
        run: echo "::set-output name=workflow_file::workflow-${GITHUB_REF#refs/heads/}.yml"

      - name: Run dynamic workflow
        uses: ./.github/actions/run-workflow
        with:
          workflow-file: ${{ steps.determine_workflow.outputs.workflow_file }}
