name: Build and Push to Google Cloud Run

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "develop"
      - "production"
  push: 
    branches:
      - "develop"
      - "production"

jobs:
  set_environment:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.set_env.outputs.env }}
    steps:
      - name: Set Environment Variables
        id: set_env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
            echo "key1=key1dev" >> $GITHUB_ENV
            echo "key2=key2dev" >> $GITHUB_ENV
            echo "key3=key3dev" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == 'refs/heads/production' ]]; then
            echo "key1=key1prod" >> $GITHUB_ENV
            echo "key2=key2prod" >> $GITHUB_ENV
            echo "key3=key3prod" >> $GITHUB_ENV
          fi
          echo "key4=key4" >> $GITHUB_ENV

  build_deploy:
    needs: set_environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          echo "Building and Deploying"
          echo ${{ needs.set_environment.outputs.env }}
          echo $key1
          echo $key2
          echo $key3
          echo $key4
