on:
  workflow_dispatch:
  pull_request:
    branches:
      - "develop"
  push:
    branches:
      - "develop"
      - "production"  # Thêm nhánh production vào đây

jobs:
  build_deploy_dev:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Build container image
        run: |
          echo "Building for development"
          for var in $(compgen -e); do
          value="${!var}"
          echo "${var}: ${value}"
          done

  build_deploy_prod:
    if: ${{ github.ref == 'refs/heads/production' }}
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: Build container image
        run: |
          echo "Building for production"
          echo ${{vars}}
