name: Build and Push to Google Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"
      - "production"
      - "feature/*"  # Các nhánh feature

jobs:
  build_deploy:
    needs: set_environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          chmod +x generate-env.sh
          ./generate-env.sh
          cat generate-env.sh
          echo "Building and Deploying"
