on:
  workflow_dispatch:
  pull_request:
    branches:
      - "develop"
  push:
    branches:
      - "develop"
      - "production"  # Thêm nhánh production vào đây

jobs:
  set_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          if [[ "${{ github.event.inputs.branch }}" == "develop" ]]; then
            echo "ENVIRONMENT=DEV" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.branch }}" == "production" ]]; then
            echo "ENVIRONMENT=PRODUCTION" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=OTHER" >> $GITHUB_ENV
          fi

  job_1:
    needs: set_environment
    runs-on: ubuntu-latest
    steps:
      - name: Use Environment Variables
        run: |
          echo "Current Environment: $ENVIRONMENT"