name: Build and Push to Google Cloud run

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "develop"
  push:
    branches:
      - "develop"
jobs:
  build_deploy:

    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Build container image
        run: |
          docker build -f Dockerfile -t inline-docker-tag .
          docker tag inline-docker-tag ${{ secrets.IMAGE_URL }}:latest
          docker tag inline-docker-tag ${{ secrets.IMAGE_URL }}:${GITHUB_RUN_ID}
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev
          docker push ${{ secrets.IMAGE_URL }} --all-tags

      - name: Deploy to Google Cloud
        run: |
          gcloud run deploy nest-hello-world-service \
          --image=${{ secrets.IMAGE_URL }}:latest \
          --allow-unauthenticated \
          --region=${{ secrets.REGION }} \
          --project=${{ secrets.PROJECT_ID }} \
          --port=3000
          --set-env-vars=[NODE_ENV=${{ env.NODE_ENV }}]
