name: staging

on:
  workflow_dispatch:
  #  pull_request:
  #    branches:
  #      - 'staging'
  push:
    branches:
      - 'staging'
jobs:
  build_deploy:
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Export Variables
        id: EXPORT_VARIABLE
        shell: bash
        run: |
          echo "staging"
