name: Build and Push to Google Cloud Run (Develop)

on:
  push:
    branches:
      - "develop"

jobs:
  build_deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Build container image
        run: |
          echo "Building for development"
          echo ${{ secrets.TEST_SECRET }}